name: Build linux

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install JDK
      run: sudo apt install default-jdk

    - name: Patch
      run: |
        sed -i '1a\#include <stdexcept>' libzt/ext/ZeroTierOne/ext/prometheus-cpp-lite-1.0/core/include/prometheus/family.h

    - name: Build
      working-directory: libzt
      run: ./build.sh host-jar "release"

    - name: Save
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: libzt/dist/linux-x64-jar-release/pkg/*.jar
